require('./components/ajax-form');
require('slick-carousel/slick/slick.js');
require('./base');
require('./components/calendar');
window.jQuery = require('jquery');
require('fotorama/fotorama');
require('./components/yamap');
require('./components/knowledge-base');
require('./components/video');
require('./components/modal-feedback');
require('./components/free-consultation');
require('./components/subscribe');
require('./components/imagePopup');
require('./components/nav');
